from __future__ import annotations

from vibe.core.config._defaults import (
    AUTO_THEME,
    DEFAULT_API_RETRY_MAX_ELAPSED_TIME,
    DEFAULT_API_TIMEOUT,
    DEFAULT_AUTO_COMPACT_THRESHOLD,
    DEFAULT_CONSOLE_BASE_URL,
    DEFAULT_MISTRAL_API_ENV_KEY,
    DEFAULT_MISTRAL_BROWSER_AUTH_API_BASE_URL,
    DEFAULT_MISTRAL_BROWSER_AUTH_BASE_URL,
    DEFAULT_MISTRAL_SERVER_URL,
    DEFAULT_THEME,
    DEFAULT_VIBE_BASE_URL,
    FALLBACK_THEME,
)
from vibe.core.config.default_orchestrator import (
    build_default_orchestrator,
    build_user_config_orchestrator,
)
from vibe.core.config.layer import (
    ConfigLayer,
    ConfigLayerError,
    ConfigPatchApplicationError,
    EmptyLayerError,
    LayerImplementationError,
    LayerNotLoadedError,
    RawConfig,
    TrustResolutionError,
    UntrustedLayerError,
)
from vibe.core.config.layers.agent_profile import AgentProfileLayer
from vibe.core.config.layers.default import DefaultConfigLayer
from vibe.core.config.layers.discovered import DiscoveredConfigLayer
from vibe.core.config.layers.growthbook import GrowthbookLayer
from vibe.core.config.models import (
    THINKING_LEVELS,
    ConnectorConfig,
    ExperimentsConfig,
    MCPHttp,
    MCPOAuth,
    MCPServer,
    MCPStaticAuth,
    MCPStdio,
    MCPStreamableHttp,
    MissingAPIKeyError,
    ModelConfig,
    OtelRedactionMode,
    OtelSpanExporterConfig,
    ProjectContextConfig,
    ProviderConfig,
    ReasoningRouterConfig,
    SessionLoggingConfig,
    ThinkingLevel,
    ThinkingMode,
    TranscribeClient,
    TranscribeModelConfig,
    TranscribeProviderConfig,
    TTSClient,
    TTSModelConfig,
    TTSProviderConfig,
)
from vibe.core.config.patch import (
    AddOperationPatch,
    ConfigPatch,
    PatchOp,
    RemoveOperationPatch,
    ReplaceOperationPatch,
)
from vibe.core.config.schema import (
    ConfigDefinitionError,
    ConfigFragment,
    ConfigSchema,
    DuplicateMergeMetadataError,
    MergeFieldMetadata,
    WithConcatMerge,
    WithConflictMerge,
    WithDeepMerge,
    WithReplaceMerge,
    WithShallowMerge,
    WithUnionMerge,
)
from vibe.core.config.types import (
    MISSING_BACKING_STORE_DATA_FINGERPRINT,
    ConfigChangeCallback,
    ConfigChangeEvent,
    LayerConfigSnapshot,
)
from vibe.core.config.vibe_schema import (
    DEFAULT_ACTIVE_MODEL_CONFIG,
    DEFAULT_MODELS,
    DEFAULT_PROVIDERS,
    DEFAULT_TRANSCRIBE_MODELS,
    DEFAULT_TRANSCRIBE_PROVIDERS,
    DEFAULT_TTS_MODELS,
    DEFAULT_TTS_PROVIDERS,
    VibeConfigSchema,
    create_default_config,
    get_persisted_config,
    load_dotenv_values,
    resolve_api_key,
)
from vibe.core.prompts import MissingPromptFileError

VibeConfigSchemaType = type[VibeConfigSchema]

__all__ = [
    "AUTO_THEME",
    "DEFAULT_ACTIVE_MODEL_CONFIG",
    "DEFAULT_API_RETRY_MAX_ELAPSED_TIME",
    "DEFAULT_API_TIMEOUT",
    "DEFAULT_AUTO_COMPACT_THRESHOLD",
    "DEFAULT_CONSOLE_BASE_URL",
    "DEFAULT_MISTRAL_API_ENV_KEY",
    "DEFAULT_MISTRAL_BROWSER_AUTH_API_BASE_URL",
    "DEFAULT_MISTRAL_BROWSER_AUTH_BASE_URL",
    "DEFAULT_MISTRAL_SERVER_URL",
    "DEFAULT_MODELS",
    "DEFAULT_PROVIDERS",
    "DEFAULT_THEME",
    "DEFAULT_TRANSCRIBE_MODELS",
    "DEFAULT_TRANSCRIBE_PROVIDERS",
    "DEFAULT_TTS_MODELS",
    "DEFAULT_TTS_PROVIDERS",
    "DEFAULT_VIBE_BASE_URL",
    "FALLBACK_THEME",
    "MISSING_BACKING_STORE_DATA_FINGERPRINT",
    "THINKING_LEVELS",
    "AddOperationPatch",
    "AgentProfileLayer",
    "ConfigChangeCallback",
    "ConfigChangeEvent",
    "ConfigDefinitionError",
    "ConfigFragment",
    "ConfigLayer",
    "ConfigLayerError",
    "ConfigPatch",
    "ConfigPatchApplicationError",
    "ConfigSchema",
    "ConnectorConfig",
    "DefaultConfigLayer",
    "DiscoveredConfigLayer",
    "DuplicateMergeMetadataError",
    "EmptyLayerError",
    "ExperimentsConfig",
    "GrowthbookLayer",
    "LayerConfigSnapshot",
    "LayerImplementationError",
    "LayerNotLoadedError",
    "MCPHttp",
    "MCPOAuth",
    "MCPServer",
    "MCPStaticAuth",
    "MCPStdio",
    "MCPStreamableHttp",
    "MergeFieldMetadata",
    "MissingAPIKeyError",
    "MissingPromptFileError",
    "ModelConfig",
    "OtelRedactionMode",
    "OtelSpanExporterConfig",
    "PatchOp",
    "ProjectContextConfig",
    "ProviderConfig",
    "RawConfig",
    "ReasoningRouterConfig",
    "RemoveOperationPatch",
    "ReplaceOperationPatch",
    "SessionLoggingConfig",
    "TTSClient",
    "TTSModelConfig",
    "TTSProviderConfig",
    "ThinkingLevel",
    "ThinkingMode",
    "TranscribeClient",
    "TranscribeModelConfig",
    "TranscribeProviderConfig",
    "TrustResolutionError",
    "UntrustedLayerError",
    "VibeConfigSchema",
    "VibeConfigSchemaType",
    "WithConcatMerge",
    "WithConflictMerge",
    "WithDeepMerge",
    "WithReplaceMerge",
    "WithShallowMerge",
    "WithUnionMerge",
    "build_default_orchestrator",
    "build_user_config_orchestrator",
    "create_default_config",
    "get_persisted_config",
    "load_dotenv_values",
    "resolve_api_key",
]
