from __future__ import annotations

from vibe.config_values import (
    AUTO_THEME as AUTO_THEME,
    DEFAULT_LOG_LEVEL as DEFAULT_LOG_LEVEL,
    DEFAULT_THEME as DEFAULT_THEME,
    FALLBACK_THEME as FALLBACK_THEME,
)

DEFAULT_MISTRAL_API_ENV_KEY = "MISTRAL_API_KEY"
DEFAULT_CONSOLE_BASE_URL = "https://console.mistral.ai"
DEFAULT_VIBE_BASE_URL = "https://chat.mistral.ai"
DEFAULT_MISTRAL_SERVER_URL = "https://api.mistral.ai"
DEFAULT_MISTRAL_BROWSER_AUTH_BASE_URL = DEFAULT_CONSOLE_BASE_URL
DEFAULT_MISTRAL_BROWSER_AUTH_API_BASE_URL = f"{DEFAULT_CONSOLE_BASE_URL}/api"
DEFAULT_API_TIMEOUT = 720.0
DEFAULT_API_RETRY_MAX_ELAPSED_TIME = 300.0
DEFAULT_AUTO_COMPACT_THRESHOLD = 200_000
